version: "3.8"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: studyportal
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    ports:
      - "4000:4000"
    environment:
      MIX_ENV: dev
    depends_on:
      - db
    volumes:
      - .:/app
    command: ["sh", "-c", "until pg_isready -h db -U postgres; do sleep 1; done && mix setup && mix phx.server"]
    stdin_open: true
    tty: true

volumes:
  postgres_data:
